# Book Database
books = {"Python Basics": {"total": 3, "available": 3, "duration": 14}, "Data Structures": {"total": 4, "available": 4, "duration": 14}, "Machine Learning": {"total": 2, "available": 2, "duration": 14}, "Artificial Intelligence": {"total": 2, "available": 2, "duration": 14},
            "Database Systems": {"total": 3, "available": 3, "duration": 14}, "Operating Systems": {"total": 3, "available": 3, "duration": 14}, "Computer Networks": {"total": 3, "available": 3, "duration": 14}, "Software Engineering": {"total": 2, "available": 2, "duration": 14},
              "Web Development": {"total": 2, "available": 2, "duration": 14}, "Mobile App Development": {"total": 2, "available": 2, "duration": 14}, "Cloud Computing": {"total": 2, "available": 2, "duration": 14}, "Rich Dad Poor Dad": {"total": 2, "available": 2, "duration": 7},
                "Atomic Habits":  {"total": 4, "available": 3, "duration": 7}, "Think and Grow Rich": {"total": 2, "available": 2, "duration": 7}, "The 7 Habits of Highly Effective People": {"total": 2, "available": 2, "duration": 7}, "Ikigai": {"total": 2, "available": 2, "duration": 7},
                  "You Can Win": {"total": 2, "available": 2, "duration": 7}, "Do Epic Shit": {"total": 2, "available": 2, "duration": 7}, "The Power of Now": {"total": 2, "available": 2, "duration": 7}, "The Art of War": {"total": 2, "available": 2, "duration": 7}, "The Prince": {"total": 2, "available": 2, "duration": 7},
                   "The_48_Laws_of_Power": {"total": 2, "available": 2, "duration": 7}, "The_Art_of_Seduction": {"total": 2, "available": 2, "duration": 7}, "Engineering_Mathematics": {"total": 2, "available": 2, "duration": 7}, "Concepts_of_Physics": {"total": 2, "available": 2, "duration": 7},
                     "Let_Us_C": {"total": 2, "available": 2, "duration": 7}, "Data_Structures_Using_C": {"total": 2, "available": 2, "duration": 7}, "Introduction_to_Algorithms": {"total": 2, "available": 2, "duration": 7}, "Computer_Networks": {"total": 2, "available": 2, "duration": 7},
                       "Operating_System_Concepts": {"total": 2, "available": 2, "duration": 7}, "Database_System_Concepts": {"total": 2, "available": 2, "duration": 7}, "Artificial_Intelligence:_A_Modern_Approach": {"total": 2, "available": 2, "duration": 7},
                          "Machine Learning: A Probabilistic Perspective": {"total": 2, "available": 2, "duration": 7}, "Wings of Fire": {"total": 2, "available": 2, "duration": 7}, "The Diary of a Young Girl": {"total": 2, "available": 2, "duration": 7},
                            "Long Walk to Freedom": {"total": 2, "available": 2, "duration": 7}, "Steve Jobs": {"total": 2, "available": 2, "duration": 7}, "Elon Musk": {"total": 2, "available": 2, "duration": 7}, "Playing It My Way": {"total": 2, "available": 2, "duration": 7}, "War and Peace": {"total": 2, "available": 2, "duration": 7},
                              "Crime and Punishment": {"total": 2, "available": 2, "duration": 7}, "The Brothers Karamazov": {"total": 2, "available": 2, "duration": 7}, "The Count of Monte Cristo": {"total": 2, "available": 2, "duration": 7}, "Les Misérables": {"total": 2, "available": 2, "duration": 7},
                                "Harry Potter and the Sorcerer's Stone": {"total": 2, "available": 2, "duration": 7}, "Harry Potter and the Chamber of Secrets": {"total": 2, "available": 2, "duration": 7}, "The Alchemist": {"total": 2, "available": 2, "duration": 7},
                                  "The Kite Runner": {"total": 2, "available": 2, "duration": 7}, "The Fault in Our Stars": {"total": 2, "available": 2, "duration": 7}}
# Issued books list (each entry = one issued copy)
issued_Books = []